# Generated by Django 4.2 on 2023-04-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expired',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
