# Generated by Django 4.2 on 2023-04-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_incoming_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
