# Generated by Django 4.2 on 2023-04-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expired_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expired',
            name='expirationDate',
        ),
        migrations.AlterField(
            model_name='expired',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
