# Generated by Django 4.2 on 2023-04-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_incoming_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='total',
        ),
    ]
