# Generated by Django 4.2 on 2023-04-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_incoming_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expired',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='quantity',
        ),
    ]
