# Generated by Django 4.2 on 2023-04-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_incoming_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='user',
            new_name='creator',
        ),
    ]
